from .level_data import LevelData


class Level:
    def __init__(self, level_json: dict) -> None:
        self.id = level_json.get("id")
        self.name = level_json.get("name")
        self.description = level_json.get("description")
        self.data = level_json.get("data")
        if self.data is not None:
            self.data = LevelData(self.data)
        self.creator = level_json.get("creator")
        self.user_id = level_json.get("user_id")
        self.level_difficulty = level_json.get("level_difficulty")
        self.official_song_id = level_json.get("official_song_id")
        self.rating = level_json.get("rating")
        self.rating_sum = level_json.get("rating_sum")
        self.downloads = level_json.get("downloads")
        self.completions = level_json.get("completions", 0)
        self.is_editable = "is_editable" in level_json
        self.has_been_verified = "has_been_verified" in level_json
        self.has_been_uploaded = "has_been_uploaded" in level_json
        self.level_version = level_json.get("level_version")
        self.game_version = level_json.get("game_version")
        self.attempts = level_json.get("attempts", 0)
        self.normal_mode_percentage = level_json.get("normal_mode_percentage", 0)
        self.practice_mode_percentage = level_json.get("practice_mode_percentage", 0)
        self.level_type = level_json.get("level_type")
        self.like_rating = level_json.get("like_rating")
        self.length = level_json.get("length")
        self.dislikes = level_json.get("dislikes")
        self.is_demon = "is_demon" in level_json
        self.stars = level_json.get("stars")
        self.feature_score = level_json.get("feature_score")
        self.is_auto = "is_auto" in level_json
        self.replay_data = level_json.get("replay_data")
        self.is_playable = "is_playable" in level_json
        self.jumps = level_json.get("jumps", 0)
        self.required_coins = level_json.get("required_coins")
        self.is_unlocked = "is_unlocked" in level_json
        self.level_size = level_json.get("level_size")
        self.build_version = level_json.get("build_version")
        self.password = level_json.get("password")
        self.original = level_json.get("original")
        self.is_two_player_mode = "is_two_player_mode" in level_json
        self.custom_song_id = level_json.get("custom_song_id")
        self.level_revision = level_json.get("level_revision")
        self.has_been_modified = "has_been_modified" in level_json
        self.object_count = level_json.get("object_count", 0)
        self.binary_version = level_json.get("binary_version")
        self.capacity_1 = level_json.get("capacity_1")
        self.capacity_2 = level_json.get("capacity_2")
        self.capacity_3 = level_json.get("capacity_3")
        self.capacity_4 = level_json.get("capacity_4")
        self.account_id = level_json.get("account_id")
        self.first_coin_has_been_acquired = "first_coin_has_been_acquired" in level_json
        self.second_coin_has_been_acquired = "second_coin_has_been_acquired" in level_json
        self.third_coin_has_been_acquired = "third_coin_has_been_acquired" in level_json
        self.total_coins = level_json.get("total_coins")
        self.coins_are_verified = "coins_are_verified" in level_json
        self.requested_stars = level_json.get("requested_stars")
        self.capacity_string = level_json.get("capacity_string")
        self.anti_cheat_has_been_triggered = "anti_cheat_has_been_triggered" in level_json
        self.has_high_object_count = "has_high_object_count" in level_json
        self.mana_orb_percentage = level_json.get("mana_orb_percentage")
        self.has_ldm = "has_ldm" in level_json
        self.ldm_is_enabled = "ldm_is_enabled" in level_json
        self.timely_id = level_json.get("timely_id")
        self.epic_rating = level_json.get("epic_rating")
        self.demon_type = level_json.get("demon_type")
        self.is_gauntlet = "is_gauntlet" in level_json
        self.is_alt_game = "is_alt_game" in level_json
        self.is_unlisted = "is_unlisted" in level_json
        self.seconds_spent_editing = level_json.get("seconds_spent_editing")
        self.seconds_spent_editing_total = level_json.get("seconds_spent_editing_total")
        self.is_level_favorited = "is_level_favorited" in level_json
        self.level_order = level_json.get("level_order")
        self.level_folder = level_json.get("level_folder")
        self.clicks = level_json.get("clicks", 0)
        self.player_time = level_json.get("player_time")
        self.level_seed = level_json.get("level_seed")
        self.level_progress = level_json.get("level_progress")
        self.vfDChk = "vfDChk" in level_json
        self.leaderboard_percentage = level_json.get("leaderboard_percentage")
        self.verification_time = level_json.get("verification_time")
        self.song_list = level_json.get("song_list")
        self.sfx_list = level_json.get("sfx_list")
        self.best_time = level_json.get("best_time")
        self.best_points = level_json.get("best_points")
        self.local_best_times = level_json.get("local_best_times")
        self.local_best_points = level_json.get("local_best_points")
        self.platformer_seed = level_json.get("platformer_seed")
        self.no_shake = level_json.get("shake_is_disabled", True)

        self.editor_camera_x_position = level_json.get("editor_camera_x_position")
        self.editor_camera_y_position = level_json.get("editor_camera_y_position")
        self.editor_camera_zoom = level_json.get("editor_camera_zoom")
        self.build_tab_page = level_json.get("build_tab_page", {})
        self.build_tab = level_json.get("build_tab")
        self.build_tab_pages = level_json.get("build_tab_pages")
        self.editor_layer = level_json.get("editor_layer")
